### ISSUE TITLE
Links are dead: ERROR 404

### ISSUE THREAD

**Issue by KES777** [renormalist/Benchmark-Perl-Formance#3]
on [site](http://renormalist.github.io/Benchmark-Perl-Formance/)

http://perlformance.net/charts/perlstone2015-f/index.html

**Comment by iynehz** [comment]
+1

It seems to me that it was the only place on the Internet that has the Perlformance data...

**Comment by renormalist** [comment]
Bummer! Indeed! I hope I didn't lose them when I had to rebuild the server. Give me some time, I will try to find them again. Or did I archive them also on github? -- I can't remember, need to swap in my brain...

**Comment by tapper** [comment]
The results are back. Yet only rendered until Perl 5.23 but at least I recovered where I left it at 2015...

**Comment by renormalist** [comment]
Too many github accounts. Anyway, as  I said I'm still back to the pasture, I mean past, I mean future. At least it's not 1996 anymore. That was the future. Once.
